### ISSUE TITLE
Clicking "New Board" during Winning/Losing 

### ISSUE THREAD

**Issue by snytbagge** [totalaj/dpp-mining-web#1]
Being impatient and clicking "New Board" while the winning or losing animations are playing, i.e. the screen shake or the circle transition causes the black overlay to stay on top of the next board, forcing the player to click "New Board" again, and skip the current board.

**Comment by totalaj** [comment]
Thanks, I suspected that may have been a problem. I will probably change the new new board button in a future update, but better safe than sorry. Fixed in commit [2b3f16b](https://github.com/totalaj/dpp-mining-web/commit/2b3f16b98bf9b4ff1afd62e46ecd1955c5f87a10)
